#!/usr/bin/env bash
#
# install_shadems.sh - install shadeMS (https://github.com/ratt-ru/shadeMS) into
# a CASA python environment, for use as a QA plotting step in the VLBI pipeline
# (e.g. rapid amp/phase-vs-time/uvdist rasters after flagging or calibration).
#
# Supports both installation modes documented in the pipeline README:
#
#   Self-contained CASA (the casa.nrao.edu tarball, its own bundled python3):
#     ./install_shadems.sh /path/to/casa-6.x.x-pyX.Y.elJ
#
#   Modular CASA (casatools/casatasks pip-installed into your own venv/conda env):
#     conda activate <your casa env>   # or: source <your venv>/bin/activate
#     ./install_shadems.sh
#
# In both cases this script only touches that one python environment - it never
# installs anything system-wide.
#
# Note: this pulls in shadeMS's full dependency chain (dask, dask-ms, datashader,
# numba/llvmlite, bokeh, holoviews, pandas, xarray, pyarrow, python-casacore,
# matplotlib, ...) - around 50 packages. On a networked/parallel filesystem
# (Lustre, CephFS, GPFS, NFS) this is I/O- not CPU-bound and can take 10-20+
# minutes even though CPU usage stays near zero throughout - that is normal,
# not a hang. It can also upgrade CASA's bundled matplotlib to satisfy shadeMS's
# requirement; casatools/casatasks themselves are left alone (this script
# verifies that at the end).
#
set -euo pipefail

usage() {
	echo "Usage:"
	echo "  $0 /path/to/casa-6.x.x-pyX.Y.elJ   # self-contained CASA"
	echo "  $0                                  # modular CASA (active python3 on \$PATH)"
	exit 1
}

[[ "${1:-}" == "-h" || "${1:-}" == "--help" ]] && usage

CASA_DIR="${1:-}"
export PIP_DISABLE_PIP_VERSION_CHECK=1
export PIP_NO_INPUT=1

if [[ -n "$CASA_DIR" ]]; then
	# ---- Self-contained ("monolithic") CASA distribution ----
	CASA_DIR="$(cd "$CASA_DIR" && pwd)"
	PY="$CASA_DIR/lib/py/bin/python3"
	LIBDIR="$CASA_DIR/lib:$CASA_DIR/lib/mpi/lib"

	if [[ ! -x "$PY" ]]; then
		echo "error: no python3 found at $PY - is this a self-contained CASA 6 tarball install?" >&2
		exit 1
	fi

	# The bundled interpreter needs CASA's own lib/ on LD_LIBRARY_PATH (for
	# libffi etc.) - CASA's bin/casa launcher normally sets this for you, but
	# calling lib/py/bin/python3 (and later lib/py/bin/shadems) directly skips
	# it, so it's set explicitly for every python3 call in this script.
	export LD_LIBRARY_PATH="$LIBDIR:${LD_LIBRARY_PATH:-}"
else
	# ---- Modular CASA: casatools/casatasks are pip packages in the active env ----
	PY="$(command -v python3)"
	LIBDIR=""

	if ! "$PY" -c "import casatools" >/dev/null 2>&1; then
		echo "error: casatools is not importable by '$PY'." >&2
		echo "       Activate your modular CASA venv/conda env first, or pass a" >&2
		echo "       self-contained CASA directory as \$1." >&2
		exit 1
	fi
fi

echo "==> Installing shadeMS into: $PY"
echo "    started: $(date)"
time "$PY" -m pip install --upgrade shadems

echo ""
echo "==> Verifying casatools/casatasks/shade_ms all still import cleanly..."
"$PY" -c "
import casatools, casatasks
casatools.table()
import shade_ms
print('OK: casatools', casatools.__file__)
print('OK: casatasks')
print('OK: shade_ms', shade_ms.__file__)
"

if [[ -n "$CASA_DIR" ]]; then
	WRAPPER="$CASA_DIR/bin/shadems"
	echo ""
	echo "==> Writing wrapper (sets LD_LIBRARY_PATH) to: $WRAPPER"
	cat > "$WRAPPER" <<WRAP
#!/usr/bin/env bash
# Auto-generated by install_shadems.sh.
# shadems's own shebang points at lib/py/bin/python3 directly, which skips the
# perl launcher (bin/casa) that normally sets LD_LIBRARY_PATH for CASA's
# bundled python3 - without it, shadems fails at import time with:
#   ImportError: libffi.so.6: cannot open shared object file
export LD_LIBRARY_PATH="$LIBDIR:\${LD_LIBRARY_PATH:-}"
exec "$CASA_DIR/lib/py/bin/shadems" "\$@"
WRAP
	chmod +x "$WRAPPER"

	"$WRAPPER" --version

	echo ""
	echo "==> Done. Call it in the pipeline (or from the shell) as:"
	echo "    $WRAPPER --xaxis TIME --yaxis amp --corr XX,YY -o qa_amp_vs_time /path/to.ms"
else
	shadems --version
	echo ""
	echo "==> Done. Call it in the pipeline (or from the shell) as:"
	echo "    shadems --xaxis TIME --yaxis amp --corr XX,YY -o qa_amp_vs_time /path/to.ms"
fi
